#!/usr/bin/env bash
# generate-sprites.sh — notchi 스프라이트 시트를 ANSI 문자열로 변환해 TypeScript 파일 생성
# Usage: bash scripts/generate-sprites.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_TS="$ROOT_DIR/src/ui/sprites.ts"
SHEETS_DIR="/tmp/notchi_sheets"
FRAMES_DIR="/tmp/notchi_frames"
BASE_URL="https://raw.githubusercontent.com/sk-ruban/notchi/main/notchi/notchi/Assets.xcassets"

# ─── 의존성 확인 ─────────────────────────────────────────────────────────────
if ! command -v chafa &>/dev/null; then
  echo "[generate-sprites] Error: chafa not found. Run: brew install chafa"
  exit 1
fi
if ! command -v magick &>/dev/null; then
  echo "[generate-sprites] Error: imagemagick not found. Run: brew install imagemagick"
  exit 1
fi

mkdir -p "$SHEETS_DIR" "$FRAMES_DIR"

# ─── 스프라이트 설정 (notchi NotchiState.swift 기반) ─────────────────────────
get_frames() {
  case "$1" in
    compacting) echo 5 ;;
    *) echo 6 ;;
  esac
}

# TUI 출력 크기 (characters)
CHAFA_WIDTH=20
CHAFA_HEIGHT=10

# ─── 스프라이트 다운로드 ──────────────────────────────────────────────────────
echo "[1/3] Downloading sprite sheets from notchi..."
for state in idle working sleeping waiting compacting; do
  for emotion in happy neutral sad sob; do
    name="${state}_${emotion}"
    out="$SHEETS_DIR/${name}.png"
    if [ ! -f "$out" ]; then
      url="$BASE_URL/${name}.imageset/sprite_sheet.png"
      code=$(curl -s -o "$out" -w "%{http_code}" "$url")
      if [ "$code" = "200" ]; then
        echo "  ✅ $name"
      else
        rm -f "$out"
        echo "  ⬜ $name (not available)"
      fi
    else
      echo "  ✓  $name (cached)"
    fi
  done
done

# ─── 프레임 분리 + ANSI 변환 ─────────────────────────────────────────────────
echo "[2/3] Splitting frames and converting to ANSI..."

# TypeScript 파일 헤더
cat > "$OUTPUT_TS" << 'TSEOF'
// AUTO-GENERATED by scripts/generate-sprites.sh
// Do not edit manually. Re-run the script to update.
//
// Source: https://github.com/sk-ruban/notchi (MIT License)
// Sprites by sk-ruban, pixel art made with Aseprite.

export type SpriteState = 'idle' | 'working' | 'sleeping' | 'waiting' | 'compacting';
export type SpriteEmotion = 'happy' | 'neutral' | 'sad' | 'sob';

/**
 * ANSI-colored frames for each state+emotion combination.
 * Each entry is an array of strings (one per frame) for animation.
 * Use \n to split lines within each frame string.
 */
export const spriteFrames: Partial<Record<`${SpriteState}_${SpriteEmotion}`, string[]>> = {
TSEOF

for state in idle working sleeping waiting compacting; do
  frames=$(get_frames "$state")
  for emotion in happy neutral sad sob; do
    name="${state}_${emotion}"
    sheet="$SHEETS_DIR/${name}.png"
    if [ ! -f "$sheet" ]; then
      continue
    fi

    frame_strings=()
    all_ok=true

    for ((i=0; i<frames; i++)); do
      frame_out="$FRAMES_DIR/${name}_${i}.png"

      # 프레임 분리
      magick "$sheet" -crop "64x64+$((i * 64))+0" +repage "$frame_out" 2>/dev/null

      # ANSI 변환 (256색, half-block 심볼, 검은 배경)
      ansi=$(chafa \
        --symbols half \
        --colors=256 \
        --bg black \
        --size="${CHAFA_WIDTH}x${CHAFA_HEIGHT}" \
        --animate=false \
        "$frame_out" 2>/dev/null)

      if [ -z "$ansi" ]; then
        all_ok=false
        break
      fi

      frame_strings+=("$ansi")
    done

    if [ "$all_ok" = false ]; then
      echo "  ⚠️  $name: conversion failed, skipping"
      continue
    fi

    echo "  ✅ $name (${frames} frames)"

    # TypeScript 배열 항목 출력
    echo "  '${name}': [" >> "$OUTPUT_TS"
    for ansi in "${frame_strings[@]}"; do
      # JSON 문자열로 이스케이프 (Python 사용)
      escaped=$(python3 -c "
import json, sys
s = sys.stdin.read()
print(json.dumps(s))
" <<< "$ansi")
      echo "    ${escaped}," >> "$OUTPUT_TS"
    done
    echo "  ]," >> "$OUTPUT_TS"
  done
done

# TypeScript 파일 푸터
cat >> "$OUTPUT_TS" << 'TSEOF'
};

/**
 * Animation FPS for each state (matches notchi NotchiState.swift).
 */
export const stateFps: Record<SpriteState, number> = {
  idle:       3,
  working:    4,
  sleeping:   2,
  waiting:    3,
  compacting: 6,
};

/**
 * Map claude-viz NodeStatus to notchi SpriteState + SpriteEmotion.
 */
export function getSprite(
  state: SpriteState,
  emotion: SpriteEmotion
): string[] | null {
  // Fallback chain: exact → sad (for sob) → neutral
  const exact = spriteFrames[`${state}_${emotion}`];
  if (exact) return exact;
  if (emotion === 'sob') {
    const sad = spriteFrames[`${state}_sad`];
    if (sad) return sad;
  }
  return spriteFrames[`${state}_neutral`] ?? null;
}
TSEOF

echo "[3/3] Done → $OUTPUT_TS"
wc -l "$OUTPUT_TS" | awk '{print "    Lines: " $1}'
